/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import DataBaseOperations.DBManagementAdmin;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;
import keeptoo.Drag;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import signup.SignUp;
import DataBaseOperations.DBManagementUser;
import javax.swing.JOptionPane;

/**
 *
 * @author RECEP
 */
public class main extends javax.swing.JFrame {
    /**
     * Creates new form main
     */
    //Global Değişkenler
    boolean isFirstAdd, isFirstUpdate = true;
    PanelColors panelColors = new PanelColors();
    DBManagementAdmin dbManagementAdmin = new DBManagementAdmin();
    DBManagementUser dbManagementUser = new DBManagementUser();
    String userName = "", templateName = "", pathForImage = "";
    JFileChooser imageChooserAdd = new JFileChooser(".");
    FolderOperations folderOperations = new FolderOperations();
    JFileChooser imageChooserUpdate = new JFileChooser(".");
    int ID;
    public main() {
        
        initComponents();
        dbManagementAdmin.displayUsers(usersTable, "");
        dbManagementAdmin.displayTemplates(templatesTable, "");
        templatePanel.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userOperations = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        templateOperations = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        templatePanel = new javax.swing.JPanel();
        addTemplatePanel = new javax.swing.JPanel();
        txtTemplateName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        btnImageAdd = new keeptoo.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTAdd = new keeptoo.KButton();
        btnFolderAdd = new keeptoo.KButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        lblAddImage = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtFolderNameAdd = new javax.swing.JTextField();
        txtImageNameAdd = new javax.swing.JTextField();
        updateTemplatePanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnTUpdate = new keeptoo.KButton();
        btnTDelete = new keeptoo.KButton();
        btnImageUpdate = new keeptoo.KButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtTemplateNameUpdate = new javax.swing.JTextField();
        lblUpdateImage = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtImageNameUpdate = new javax.swing.JTextField();
        tablePanel1 = new javax.swing.JScrollPane();
        templatesTable = new javax.swing.JTable();
        txtTemplateSearch = new javax.swing.JTextField();
        btnTemplateSearch = new keeptoo.KButton();
        userPanel = new javax.swing.JPanel();
        addUserPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtUsernameAdd = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnAdd = new keeptoo.KButton();
        jLabel15 = new javax.swing.JLabel();
        txtPasswordAdd = new javax.swing.JPasswordField();
        lblSHAdd = new javax.swing.JLabel();
        updateUserPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnDelete = new keeptoo.KButton();
        jLabel14 = new javax.swing.JLabel();
        txtUsernameUpdate = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtPasswordUpdate = new javax.swing.JPasswordField();
        lblSHUpdate = new javax.swing.JLabel();
        btnUpdate2 = new keeptoo.KButton();
        tablePanel = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        txtUserSearch = new javax.swing.JTextField();
        btnUserSearch = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basePanel.setBackground(new java.awt.Color(255, 255, 255));
        basePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                basePanelMouseDragged(evt);
            }
        });
        basePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                basePanelMousePressed(evt);
            }
        });
        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(54, 33, 89));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Admin İşlemleri");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 220, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\admin30.png")); // NOI18N
        leftPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 50));

        userOperations.setBackground(new java.awt.Color(64, 43, 100));
        userOperations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userOperationsMousePressed(evt);
            }
        });
        userOperations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\user30.png")); // NOI18N
        userOperations.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Üye İşlemleri");
        userOperations.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 176, 32));

        leftPanel.add(userOperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 330, 70));
        leftPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 60));

        templateOperations.setBackground(new java.awt.Color(64, 43, 100));
        templateOperations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                templateOperationsMousePressed(evt);
            }
        });
        templateOperations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Template İşlemleri");
        templateOperations.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 176, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\settings30.png")); // NOI18N
        templateOperations.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 30));

        leftPanel.add(templateOperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 330, 70));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 80));

        basePanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 740));

        topPanel.setBackground(new java.awt.Color(51, 0, 102));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\close30w.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        topPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 40));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("KeepHTML");
        topPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));
        topPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 10));

        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("We 🖤  KeepHTML");
        topPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 0, 153));
        jSeparator3.setForeground(new java.awt.Color(102, 0, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        topPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("*TemplateDüzenleme Ve Silme işlemleri için aşağıdaki tablodan ilgili satırı seçmeniz gerekmektedir.");
        topPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 570, 30));

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(204, 204, 204));
        lblExit.setText("Çıkış Yap");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        topPanel.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, 20));

        basePanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1030, 100));

        templatePanel.setBackground(new java.awt.Color(255, 255, 255));
        templatePanel.setMinimumSize(new java.awt.Dimension(930, 590));
        templatePanel.setPreferredSize(new java.awt.Dimension(930, 590));
        templatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTemplatePanel.setBackground(new java.awt.Color(51, 0, 102));
        addTemplatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTemplateName.setBackground(new Color(0,0,0,0));
        txtTemplateName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtTemplateName.setForeground(new java.awt.Color(255, 255, 255));
        txtTemplateName.setBorder(null);
        txtTemplateName.setOpaque(false);
        addTemplatePanel.add(txtTemplateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        addTemplatePanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 370, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Yeni Template");
        addTemplatePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 40));

        btnImageAdd.setText("Seç...");
        btnImageAdd.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnImageAdd.setkBorderRadius(0);
        btnImageAdd.setkEndColor(new java.awt.Color(102, 0, 102));
        btnImageAdd.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnImageAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnImageAdd.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnImageAdd.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnImageAdd.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnImageAdd.setkStartColor(new java.awt.Color(204, 204, 255));
        btnImageAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImageAddMouseClicked(evt);
            }
        });
        btnImageAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageAddActionPerformed(evt);
            }
        });
        addTemplatePanel.add(btnImageAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 80, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\folder30.png")); // NOI18N
        addTemplatePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\template30.png")); // NOI18N
        addTemplatePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 30));

        btnTAdd.setText("Ekle");
        btnTAdd.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnTAdd.setkBorderRadius(20);
        btnTAdd.setkEndColor(new java.awt.Color(102, 0, 102));
        btnTAdd.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnTAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTAdd.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnTAdd.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnTAdd.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnTAdd.setkStartColor(new java.awt.Color(204, 204, 255));
        btnTAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTAddMouseClicked(evt);
            }
        });
        btnTAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAddActionPerformed(evt);
            }
        });
        btnTAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnTAddKeyTyped(evt);
            }
        });
        addTemplatePanel.add(btnTAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, 30));

        btnFolderAdd.setText("Seç...");
        btnFolderAdd.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnFolderAdd.setkBorderRadius(0);
        btnFolderAdd.setkEndColor(new java.awt.Color(102, 0, 102));
        btnFolderAdd.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnFolderAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnFolderAdd.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnFolderAdd.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnFolderAdd.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnFolderAdd.setkStartColor(new java.awt.Color(204, 204, 255));
        btnFolderAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFolderAddMouseClicked(evt);
            }
        });
        btnFolderAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderAddActionPerformed(evt);
            }
        });
        addTemplatePanel.add(btnFolderAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 80, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\image30.png")); // NOI18N
        addTemplatePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, -1));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        addTemplatePanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 370, 10));
        addTemplatePanel.add(lblAddImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 100));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        addTemplatePanel.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 10));

        txtFolderNameAdd.setEditable(false);
        txtFolderNameAdd.setBackground(new Color(0,0,0,0));
        txtFolderNameAdd.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txtFolderNameAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtFolderNameAdd.setBorder(null);
        txtFolderNameAdd.setOpaque(false);
        addTemplatePanel.add(txtFolderNameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 290, 30));

        txtImageNameAdd.setEditable(false);
        txtImageNameAdd.setBackground(new Color(0,0,0,0));
        txtImageNameAdd.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txtImageNameAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtImageNameAdd.setBorder(null);
        txtImageNameAdd.setOpaque(false);
        addTemplatePanel.add(txtImageNameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 30));

        templatePanel.add(addTemplatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 440, 230));

        updateTemplatePanel.setBackground(new java.awt.Color(51, 0, 102));
        updateTemplatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Template Düzenleme ve Silme");
        updateTemplatePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 220, 30));

        btnTUpdate.setText("Düzenle");
        btnTUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTUpdate.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnTUpdate.setkBorderRadius(20);
        btnTUpdate.setkEndColor(new java.awt.Color(153, 51, 255));
        btnTUpdate.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnTUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTUpdate.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnTUpdate.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnTUpdate.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnTUpdate.setkStartColor(new java.awt.Color(204, 204, 255));
        btnTUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTUpdateMouseClicked(evt);
            }
        });
        updateTemplatePanel.add(btnTUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 30));

        btnTDelete.setText("Sil");
        btnTDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTDelete.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnTDelete.setkBorderRadius(20);
        btnTDelete.setkEndColor(new java.awt.Color(153, 51, 255));
        btnTDelete.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnTDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTDelete.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnTDelete.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnTDelete.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnTDelete.setkStartColor(new java.awt.Color(204, 204, 255));
        btnTDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTDeleteMouseClicked(evt);
            }
        });
        updateTemplatePanel.add(btnTDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 30));

        btnImageUpdate.setText("Seç...");
        btnImageUpdate.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnImageUpdate.setkBorderRadius(0);
        btnImageUpdate.setkEndColor(new java.awt.Color(102, 0, 102));
        btnImageUpdate.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnImageUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnImageUpdate.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnImageUpdate.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnImageUpdate.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnImageUpdate.setkStartColor(new java.awt.Color(204, 204, 255));
        btnImageUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImageUpdateMouseClicked(evt);
            }
        });
        btnImageUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageUpdateActionPerformed(evt);
            }
        });
        updateTemplatePanel.add(btnImageUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 80, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\image30.png")); // NOI18N
        updateTemplatePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 30, -1));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        updateTemplatePanel.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 370, 10));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\template30.png")); // NOI18N
        updateTemplatePanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        txtTemplateNameUpdate.setBackground(new Color(0,0,0,0));
        txtTemplateNameUpdate.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtTemplateNameUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtTemplateNameUpdate.setBorder(null);
        txtTemplateNameUpdate.setOpaque(false);
        updateTemplatePanel.add(txtTemplateNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 190, 30));
        updateTemplatePanel.add(lblUpdateImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 100));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        updateTemplatePanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 10));

        txtImageNameUpdate.setEditable(false);
        txtImageNameUpdate.setBackground(new Color(0,0,0,0));
        txtImageNameUpdate.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txtImageNameUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtImageNameUpdate.setBorder(null);
        txtImageNameUpdate.setOpaque(false);
        updateTemplatePanel.add(txtImageNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 290, 30));

        templatePanel.add(updateTemplatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 440, 230));

        tablePanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 204)));
        tablePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePanel1MouseClicked(evt);
            }
        });

        templatesTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        templatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Liste Numarası", "Template Adı", "Uzantısı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        templatesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                templatesTableMouseClicked(evt);
            }
        });
        tablePanel1.setViewportView(templatesTable);
        if (templatesTable.getColumnModel().getColumnCount() > 0) {
            templatesTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        templatePanel.add(tablePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 890, 300));

        txtTemplateSearch.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtTemplateSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 153)));
        templatePanel.add(txtTemplateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 780, 40));

        btnTemplateSearch.setText("Ara");
        btnTemplateSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTemplateSearch.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnTemplateSearch.setkBorderRadius(20);
        btnTemplateSearch.setkEndColor(new java.awt.Color(153, 51, 255));
        btnTemplateSearch.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnTemplateSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTemplateSearch.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnTemplateSearch.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnTemplateSearch.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnTemplateSearch.setkStartColor(new java.awt.Color(204, 204, 255));
        btnTemplateSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemplateSearchActionPerformed(evt);
            }
        });
        templatePanel.add(btnTemplateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 100, 40));

        basePanel.add(templatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 1030, 640));

        userPanel.setBackground(new java.awt.Color(255, 255, 255));
        userPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addUserPanel.setBackground(new java.awt.Color(51, 0, 102));
        addUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\password30.png")); // NOI18N
        addUserPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 30, 30));

        txtUsernameAdd.setBackground(new Color(0,0,0,0));
        txtUsernameAdd.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtUsernameAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameAdd.setBorder(null);
        txtUsernameAdd.setOpaque(false);
        addUserPanel.add(txtUsernameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        addUserPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        addUserPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Yeni Üyelik");
        addUserPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 40));

        btnAdd.setText("Ekle");
        btnAdd.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnAdd.setkBorderRadius(20);
        btnAdd.setkEndColor(new java.awt.Color(102, 0, 102));
        btnAdd.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAdd.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnAdd.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnAdd.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnAdd.setkStartColor(new java.awt.Color(204, 204, 255));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        addUserPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\user30.png")); // NOI18N
        addUserPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 40, 30));

        txtPasswordAdd.setBackground(new Color(0,0,0,0));
        txtPasswordAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPasswordAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordAdd.setBorder(null);
        txtPasswordAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPasswordAdd.setOpaque(false);
        addUserPanel.add(txtPasswordAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 160, 30));

        lblSHAdd.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSHAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblSHAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\eye30.png")); // NOI18N
        lblSHAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSHAddMousePressed(evt);
            }
        });
        addUserPanel.add(lblSHAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 30));

        userPanel.add(addUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, 190));

        updateUserPanel.setBackground(new java.awt.Color(51, 0, 102));
        updateUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Üye Düzenleme Ve Silme");
        updateUserPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 180, 30));

        btnDelete.setText("Sil");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnDelete.setkBorderRadius(20);
        btnDelete.setkEndColor(new java.awt.Color(153, 51, 255));
        btnDelete.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelete.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnDelete.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnDelete.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnDelete.setkStartColor(new java.awt.Color(204, 204, 255));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        updateUserPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 100, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\user30.png")); // NOI18N
        updateUserPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 40, -1));

        txtUsernameUpdate.setBackground(new Color(0,0,0,0));
        txtUsernameUpdate.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtUsernameUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameUpdate.setBorder(null);
        txtUsernameUpdate.setOpaque(false);
        updateUserPanel.add(txtUsernameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 190, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        updateUserPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        updateUserPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\password30.png")); // NOI18N
        updateUserPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        txtPasswordUpdate.setBackground(new Color(0,0,0,0));
        txtPasswordUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPasswordUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordUpdate.setBorder(null);
        txtPasswordUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPasswordUpdate.setOpaque(false);
        updateUserPanel.add(txtPasswordUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 30));

        lblSHUpdate.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSHUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblSHUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\RECEP\\Documents\\NetBeansProjects\\KeepHTML\\data\\images\\static\\eye30.png")); // NOI18N
        lblSHUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSHUpdateMousePressed(evt);
            }
        });
        updateUserPanel.add(lblSHUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        btnUpdate2.setText("Düzenle");
        btnUpdate2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate2.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnUpdate2.setkBorderRadius(20);
        btnUpdate2.setkEndColor(new java.awt.Color(153, 51, 255));
        btnUpdate2.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnUpdate2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate2.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnUpdate2.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnUpdate2.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnUpdate2.setkStartColor(new java.awt.Color(204, 204, 255));
        btnUpdate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate2MouseClicked(evt);
            }
        });
        updateUserPanel.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, 30));

        userPanel.add(updateUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 480, 190));

        tablePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 204)));

        usersTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcı Adı", "Parola"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        tablePanel.setViewportView(usersTable);
        if (usersTable.getColumnModel().getColumnCount() > 0) {
            usersTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        userPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 890, 300));

        txtUserSearch.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtUserSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 153)));
        userPanel.add(txtUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 780, 40));

        btnUserSearch.setText("Ara");
        btnUserSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserSearch.setkBackGroundColor(new java.awt.Color(153, 153, 255));
        btnUserSearch.setkBorderRadius(20);
        btnUserSearch.setkEndColor(new java.awt.Color(153, 51, 255));
        btnUserSearch.setkHoverEndColor(new java.awt.Color(204, 153, 255));
        btnUserSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUserSearch.setkHoverStartColor(new java.awt.Color(153, 204, 255));
        btnUserSearch.setkPressedColor(new java.awt.Color(153, 153, 255));
        btnUserSearch.setkSelectedColor(new java.awt.Color(153, 51, 255));
        btnUserSearch.setkStartColor(new java.awt.Color(204, 204, 255));
        btnUserSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseClicked(evt);
            }
        });
        userPanel.add(btnUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 100, 40));

        basePanel.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 1030, 640));

        getContentPane().add(basePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void reSizeImage(JLabel label)
    {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(pathForImage));
            Image dimg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            label.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }
      
    }
    private void userOperationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOperationsMousePressed
        // TODO add your handling code here:
        panelColors.setColor(userOperations,new Color(85,65,118));
        panelColors.setColor(templateOperations,new Color(64,43,100));
        templatePanel.setVisible(false);
        userPanel.setVisible(true);

    }//GEN-LAST:event_userOperationsMousePressed

    private void templateOperationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_templateOperationsMousePressed
        // TODO add your handling code here:
        panelColors.setColor(userOperations,new Color(64,43,100));
        panelColors.setColor(templateOperations,new Color(85,65,118));
        templatePanel.setVisible(true);
        userPanel.setVisible(false);
    }//GEN-LAST:event_templateOperationsMousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void basePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basePanelMousePressed
            new Drag(basePanel).onPress(evt);
    }//GEN-LAST:event_basePanelMousePressed

    private void basePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basePanelMouseDragged
        new Drag(basePanel).moveWindow(evt);
    }//GEN-LAST:event_basePanelMouseDragged

    private void lblSHAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSHAddMousePressed
        // TODO add your handling code here:
        if(isFirstAdd){
            txtPasswordAdd.setEchoChar((char)0);
            isFirstAdd = false;    
        }
        else{
            txtPasswordAdd.setEchoChar('*');
            isFirstAdd = true;  
        }
    }//GEN-LAST:event_lblSHAddMousePressed

    private void lblSHUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSHUpdateMousePressed
        // TODO add your handling code here:
        if(isFirstUpdate){
            txtPasswordUpdate.setEchoChar((char)0);
            isFirstUpdate = false;    
        }
        else{
            txtPasswordUpdate.setEchoChar('*');
            isFirstUpdate = true;  
        }
    }//GEN-LAST:event_lblSHUpdateMousePressed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        String password = new String(txtPasswordAdd.getPassword());
        
        if(txtUsernameAdd.getText().length() != 0 && password.length() != 0){
            if(dbManagementAdmin.addUser(txtUsernameAdd.getText(),password ,0) == 1)
            {
                folderOperations.createFolder(txtUsernameAdd.getText(),"\\data\\users\\");
                dbManagementAdmin.displayUsers(usersTable,"");
                System.out.println("Kayıt Başarılı");
                ArrayList<JTextField> fields = new ArrayList<JTextField>();
                fields.add(txtUsernameAdd);
                fields.add(txtPasswordAdd);
                dbManagementAdmin.resetFields(fields);
            }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        // TODO add your handling code here:
        userName = usersTable.getValueAt(usersTable.getSelectedRow(), 0).toString();
        dbManagementAdmin.fillFieldsUser(txtUsernameUpdate, txtPasswordUpdate);
    }//GEN-LAST:event_usersTableMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        String path = path = Paths.get("").toAbsolutePath().toString();
        int answer = JOptionPane.showConfirmDialog(null, "Silinecek kullanıcının verilerini arşive eklemek ister misiniz?", "Arşiv", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION)
        {
            try {
                folderOperations.createFolder(txtUsernameUpdate.getText(), "\\data\\userArchive\\");
                folderOperations.copyFrom(path + "\\data\\userarchive\\" + txtUsernameUpdate.getText(), path + "\\data\\users\\" + txtUsernameUpdate.getText());
                
            }catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(dbManagementAdmin.deleteUser(txtUsernameUpdate.getText()) == 1){
          System.out.println("Kayıt Silme Başarılı");
          folderOperations.deleteFolder(path + "\\data\\users\\" + txtUsernameUpdate.getText());
          dbManagementAdmin.displayUsers(usersTable,"");
          
          ArrayList<JTextField> fields = new ArrayList<JTextField>();
          fields.add(txtUsernameUpdate);
          fields.add(txtPasswordUpdate);
          dbManagementAdmin.resetFields(fields);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnImageAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageAddMouseClicked
        // TODO add your handling code here:
        int response;
        String open = ".";
       
        imageChooserAdd.setFileSelectionMode(JFileChooser.FILES_ONLY);
        response = imageChooserAdd.showOpenDialog(null);

        if(response == JFileChooser.APPROVE_OPTION)
        {
            open = imageChooserAdd.getSelectedFile().getAbsolutePath().toString();
            txtImageNameAdd.setText(open);
            pathForImage = open;
            reSizeImage(lblAddImage);
        }
    }//GEN-LAST:event_btnImageAddMouseClicked

    private void btnImageAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImageAddActionPerformed

    private void btnTUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTUpdateMouseClicked
        // TODO add your handling code here:
        String fileName = ""; 
        if(imageChooserUpdate.getSelectedFile() != null)
        {
            File f = imageChooserUpdate.getSelectedFile();
            fileName = f.getAbsolutePath();
        }
        else{
            fileName = txtImageNameUpdate.getText();
        }
        fileName = fileName.replace('\\', '/');
        if(dbManagementAdmin.updateTemplate(txtTemplateNameUpdate.getText(),fileName , lblUpdateImage, ID) == 1){
            dbManagementAdmin.displayTemplates(templatesTable, "");
            System.out.println("Template Güncelleme Başarılı");
            //folderOperations.renameFolder(txtUsernameUpdate.getText(), userName, "\\data\\users\\");
            folderOperations.renameFolder(txtTemplateNameUpdate.getText(), templateName, "\\data\\templates\\");
            lblUpdateImage.setIcon(null);
            //folderOperations.renameFolder(txtUsernameUpdate.getText(), userName);
            ArrayList<JTextField> fields = new ArrayList<JTextField>();
            fields.add(txtTemplateNameUpdate);
            fields.add(txtImageNameUpdate);
            dbManagementAdmin.resetFields(fields);
        }
       
    }//GEN-LAST:event_btnTUpdateMouseClicked

    private void btnTDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTDeleteMouseClicked
        // TODO add your handling code here:
        if(dbManagementAdmin.deleteTemplate(ID) == 1){
            dbManagementAdmin.displayTemplates(templatesTable, "");
            System.out.println("Template Silme Başarılı");
            ArrayList<JTextField> fields = new ArrayList<JTextField>();
            fields.add(txtImageNameUpdate);
            fields.add(txtTemplateNameUpdate);
            lblUpdateImage.setIcon(null);
            dbManagementAdmin.resetFields(fields);
        }
    }//GEN-LAST:event_btnTDeleteMouseClicked

    private void templatesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_templatesTableMouseClicked
        // TODO add your handling code here:
       /* if(templatesTable.getSelectedRowCount()> 0)
        {*/
            ID = Integer.parseInt(templatesTable.getValueAt(templatesTable.getSelectedRow(), 0).toString());
            pathForImage = templatesTable.getValueAt(templatesTable.getSelectedRow(), 2).toString();
            templateName = templatesTable.getValueAt(templatesTable.getSelectedRow(), 1).toString();
            dbManagementAdmin.fillFieldsTemplate(txtImageNameUpdate, txtTemplateNameUpdate);
            
            //Labela fotoğraf ekleme
            reSizeImage(lblUpdateImage);
      //  }
         
    }//GEN-LAST:event_templatesTableMouseClicked

    private void btnTAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTAddMouseClicked
        // TODO add your handling code here:
        String fileName = "";
        String path = path = Paths.get("").toAbsolutePath().toString();
        if(imageChooserUpdate.getSelectedFile() != null)
        {
            File f = imageChooserAdd.getSelectedFile();
            fileName = f.getAbsolutePath();
        }
        else{
            fileName = txtImageNameAdd.getText();
        }
        fileName = fileName.replace('\\', '/');
        if(dbManagementAdmin.addTemplate(txtTemplateName.getText(), fileName, lblAddImage) == 1)
        {
            dbManagementAdmin.displayTemplates(templatesTable, "");
            System.out.println("Template Ekleme Başarılı");
            folderOperations.createFolder(txtTemplateName.getText(),"\\data\\templates\\");
            try {
                folderOperations.copyFrom(path + "\\data\\templates\\" + txtTemplateName.getText() + "\\" ,txtFolderNameAdd.getText());
            } catch (IOException ex) {
                Date now = new Date();
                dbManagementUser.callStoredError(ex.getClass().getName(), -1,ex.getMessage(),now.toString());
                System.out.println("Exception Hatası: "+ex.getMessage());
                System.out.println("Exception Cause: "+ ex.getCause());
            }
            lblAddImage.setIcon(null);
            ArrayList<JTextField> fields = new ArrayList<JTextField>();
            fields.add(txtTemplateName);
            fields.add(txtImageNameAdd);
            fields.add(txtFolderNameAdd);
            dbManagementAdmin.resetFields(fields);
        }
        
        
        
    }//GEN-LAST:event_btnTAddMouseClicked

    private void btnTAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTAddActionPerformed

    private void btnFolderAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFolderAddMouseClicked
        // TODO add your handling code here:
        int response;
        String open = ".";
        JFileChooser jFileChooser = new JFileChooser(".");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        response = jFileChooser.showOpenDialog(null);

        if(response == JFileChooser.APPROVE_OPTION)
        {
            open = jFileChooser.getSelectedFile().getAbsolutePath().toString();
            txtFolderNameAdd.setText(open);
        }
    }//GEN-LAST:event_btnFolderAddMouseClicked

    private void btnFolderAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFolderAddActionPerformed

    private void btnImageUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageUpdateMouseClicked
        // TODO add your handling code here:
        int response;
        String open = ".";
        imageChooserUpdate.setFileSelectionMode(JFileChooser.FILES_ONLY);
        response = imageChooserUpdate.showOpenDialog(null);

        if(response == JFileChooser.APPROVE_OPTION)
        {
            open = imageChooserUpdate.getSelectedFile().getAbsolutePath().toString();
            txtImageNameUpdate.setText(open);
            pathForImage = open;
            reSizeImage(lblUpdateImage);
        }
    }//GEN-LAST:event_btnImageUpdateMouseClicked

    private void btnImageUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImageUpdateActionPerformed

    private void btnTAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTAddKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTAddKeyTyped

    private void tablePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePanel1MouseClicked
        // TODO add your handling code here:
        templateName = templatesTable.getValueAt(templatesTable.getSelectedRow(), 1).toString();
    }//GEN-LAST:event_tablePanel1MouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        signup.SignUp login = new SignUp();
        login.show();
        this.hide();
    }//GEN-LAST:event_lblExitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        File file = new File("C:\\Users\\RECEP\\Desktop\\MOSCHINO_blog\\HTML-Moschino1.0.0\\about.html");
        DynamicLabelMotor dynamicLabelMotor = new DynamicLabelMotor(file, "</a>");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2MouseClicked

    private void btnTemplateSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemplateSearchActionPerformed
        // TODO add your handling code here:
        dbManagementAdmin.displayTemplates(templatesTable, txtTemplateSearch.getText());
        
    }//GEN-LAST:event_btnTemplateSearchActionPerformed

    private void btnUserSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseClicked
        // TODO add your handling code here:
        dbManagementAdmin.displayUsers(usersTable, txtUserSearch.getText());
    }//GEN-LAST:event_btnUserSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addTemplatePanel;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JPanel basePanel;
    private keeptoo.KButton btnAdd;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnFolderAdd;
    private keeptoo.KButton btnImageAdd;
    private keeptoo.KButton btnImageUpdate;
    private keeptoo.KButton btnTAdd;
    private keeptoo.KButton btnTDelete;
    private keeptoo.KButton btnTUpdate;
    private keeptoo.KButton btnTemplateSearch;
    private keeptoo.KButton btnUpdate2;
    private keeptoo.KButton btnUserSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAddImage;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblSHAdd;
    private javax.swing.JLabel lblSHUpdate;
    private javax.swing.JLabel lblUpdateImage;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JScrollPane tablePanel1;
    private javax.swing.JPanel templateOperations;
    private javax.swing.JPanel templatePanel;
    private javax.swing.JTable templatesTable;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtFolderNameAdd;
    private javax.swing.JTextField txtImageNameAdd;
    private javax.swing.JTextField txtImageNameUpdate;
    private javax.swing.JPasswordField txtPasswordAdd;
    private javax.swing.JPasswordField txtPasswordUpdate;
    private javax.swing.JTextField txtTemplateName;
    private javax.swing.JTextField txtTemplateNameUpdate;
    private javax.swing.JTextField txtTemplateSearch;
    private javax.swing.JTextField txtUserSearch;
    private javax.swing.JTextField txtUsernameAdd;
    private javax.swing.JTextField txtUsernameUpdate;
    private javax.swing.JPanel updateTemplatePanel;
    private javax.swing.JPanel updateUserPanel;
    private javax.swing.JPanel userOperations;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
