/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import DataBaseOperations.DBManagementUser;
import admin.PanelColors;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import keeptoo.Drag;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author RECEP
 */
public class RouterTemplates extends javax.swing.JFrame {

    /**
     * Creates new form RouterTemplates
     */
    DBManagementUser dBManagementUser = new DBManagementUser();

    public RouterTemplates() {
    
        initComponents();
        middlePanel.removeAll();
        dBManagementUser.displayTemplates(middlePanel, txtPage, lblTotalPage,"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTemplate2 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        marginPanel = new javax.swing.JPanel();
        txtPage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblTotalPage = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(122, 22, 221));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        topPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("  X");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel35MousePressed(evt);
            }
        });
        topPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 60, 60));

        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("We 🖤  KeepHTML");
        topPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 40));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("KeepHTML");
        topPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        txtSearch.setBackground(new java.awt.Color(122, 22, 221));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setText("Moschin...");
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        topPanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 470, 40));
        topPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 500, 20));

        lblTemplate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/images/icons8-google-web-search-50.png"))); // NOI18N
        lblTemplate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTemplate2MouseEntered(evt);
            }
        });
        topPanel.add(lblTemplate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 30, 40));

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(204, 204, 204));
        lblExit.setText("Çıkış Yap");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        topPanel.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 60, 30));

        jPanel1.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 250));

        middlePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.add(middlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1470, 650));

        marginPanel.setOpaque(false);

        txtPage.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtPage.setForeground(new java.awt.Color(122, 22, 221));
        txtPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPage.setText("1");
        txtPage.setBorder(null);
        txtPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPageActionPerformed(evt);
            }
        });
        txtPage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPageKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 204));
        jLabel10.setText("  /");
        jLabel10.setRequestFocusEnabled(false);

        lblTotalPage.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTotalPage.setForeground(new java.awt.Color(102, 0, 204));
        lblTotalPage.setText("1");
        lblTotalPage.setRequestFocusEnabled(false);

        jSeparator3.setForeground(new java.awt.Color(122, 22, 221));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        javax.swing.GroupLayout marginPanelLayout = new javax.swing.GroupLayout(marginPanel);
        marginPanel.setLayout(marginPanelLayout);
        marginPanelLayout.setHorizontalGroup(
            marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginPanelLayout.createSequentialGroup()
                .addGap(643, 643, 643)
                .addGroup(marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(747, Short.MAX_VALUE))
        );
        marginPanelLayout.setVerticalGroup(
            marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginPanelLayout.createSequentialGroup()
                .addGroup(marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalPage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(marginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 890, 1470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1468, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    PanelColors panelColors = new PanelColors();
   
    private void jLabel35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MousePressed
       System.exit(0);
    }//GEN-LAST:event_jLabel35MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        new Drag(jPanel1).moveWindow(evt);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        new Drag(jPanel1).onPress(evt);
    }//GEN-LAST:event_jPanel1MousePressed

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        new Drag(topPanel).onPress(evt);
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        new Drag(topPanel).moveWindow(evt);
    }//GEN-LAST:event_topPanelMouseDragged

    private void txtPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPageActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        SignUp login = new SignUp();
        login.show();
        this.hide();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblTemplate2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTemplate2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTemplate2MouseEntered

    private void txtPageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPageKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            middlePanel.removeAll();
            dBManagementUser.displayTemplates(middlePanel, txtPage, lblTotalPage,"");
        }
    }//GEN-LAST:event_txtPageKeyPressed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            dBManagementUser.displayTemplates(middlePanel, txtPage, lblTotalPage,txtSearch.getText());
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RouterTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RouterTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RouterTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RouterTemplates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RouterTemplates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblTemplate2;
    private javax.swing.JLabel lblTotalPage;
    private javax.swing.JPanel marginPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtPage;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
