/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import DataBaseOperations.DBManagementUser;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Paths;
import keeptoo.Drag;
import java.sql.*;
import javax.swing.JOptionPane;
import admin.main;
import java.util.Date;
/**
 *
 * @author RECEP
 */
public class SignUp extends javax.swing.JFrame {

    
    /**
     * Creates new form SignUp
     */
    String userName = "";
    String password = "";
    int isTrue = 0;
    Connection connection = null;
    DbHelper helper = new DbHelper();
    DBManagementUser dbManagementUser = new DBManagementUser();
    public static String userID = "null";
    
    
    public SignUp() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnUser = new keeptoo.KButton();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblKeepHTML = new javax.swing.JLabel();
        lblUserLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(851, 522));
        setName("login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(851, 522));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 51, 255));
        kGradientPanel1.setkGradientFocus(-200);
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 0, 102));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUser.setBorder(null);
        btnUser.setText("Giriş Yap");
        btnUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUser.setkBorderRadius(40);
        btnUser.setkEndColor(new java.awt.Color(0, 0, 102));
        btnUser.setkHoverEndColor(new java.awt.Color(255, 102, 255));
        btnUser.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUser.setkHoverStartColor(new java.awt.Color(51, 0, 102));
        btnUser.setkStartColor(new java.awt.Color(255, 102, 255));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 329, 160, 40));

        txtPassword.setBackground(new Color(0,0,0,0));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPassword.setOpaque(false);
        kGradientPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 348, 50));

        txtUsername.setBackground(new Color(0,0,0,0));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.setCaretColor(new java.awt.Color(204, 0, 204));
        txtUsername.setOpaque(false);
        kGradientPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 348, 50));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword.setText("Parola");
        kGradientPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, 20));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(204, 204, 204));
        lblUsername.setText("Kullanıcı Adı");
        kGradientPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 10));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblExit.setForeground(new java.awt.Color(153, 0, 153));
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 60));

        lblKeepHTML.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        lblKeepHTML.setForeground(new java.awt.Color(204, 204, 204));
        lblKeepHTML.setText("KeepHTML");
        lblKeepHTML.setRequestFocusEnabled(false);
        kGradientPanel1.add(lblKeepHTML, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 50));

        lblUserLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/group.png"))); // NOI18N
        kGradientPanel1.add(lblUserLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 90));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        new Drag(kGradientPanel1).moveWindow(evt);

    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        userName = txtUsername.getText();
        password = new String(txtPassword.getPassword());
        
        try {
            int whoIs = dbManagementUser.checkUser(userName,password);
            switch (whoIs) {
                case 1:
                    RouterTemplates routerTemplates = new RouterTemplates();
                    routerTemplates.show();
                    this.hide();
                    userID = txtUsername.getText();
                    break;
                case 2:
                    admin.main mainFrame = new main();
                    mainFrame.show();
                    this.hide();

                    userID = txtUsername.getText();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Yanlış kullanıcı adı/parola girdiniz", "InfoBox: Hatalı Giriş", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        } catch (SQLException ex) {
           helper.showErrorMessage(ex);
           Date now = new Date();
            dbManagementUser.callStoredError(ex.getClass().getName(), ex.getErrorCode(),ex.getMessage(),now.toString());
        }
        catch(Exception ex)
        {
           Date now = new Date();
           dbManagementUser.callStoredError(ex.getClass().getName(), -1,ex.getMessage(),now.toString());
        }
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnUser;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblKeepHTML;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserLogo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
