
/**
 *
 * @author RECEP
 */
package signup;

import admin.PanelColors;
import java.io.File;
import javax.swing.JOptionPane;
import java.awt.*;
import java.nio.file.Paths;
import keeptoo.Drag;

public class webSite extends javax.swing.JFrame {

    String path = Paths.get("").toAbsolutePath().toString();
    /**
     * Creates new form webSite
     */
    PanelColors panelColors = new PanelColors();
    DynamiclyEvents dynamiclyEvents = new DynamiclyEvents();
    public webSite() {
        initComponents();
        File file = new File(path + "\\data\\templates\\Moschino\\about.html");
        BasePattern basePattern = new BasePattern(file);
        txtTittle.setText(basePattern.getData("keepbasetittle='editableStart'", "keepbasetittle='editableFinish'"));
        txtSlogan.setText(basePattern.getData("keepslogan='editableStart'", "keepslogan='editableFinish'"));
        txtContent.setText(basePattern.getData("keepstatement='editableStart'", "keepstatement='editableFinish'"));
        txtContentTittle.setText(basePattern.getData("keeptittle='editableStart'", "keeptittle='editableFinish'"));
        txtSignature.setText(basePattern.getData("keepsignature='editableStart'", "keepsignature='editableFinish'"));
        lblSiteName.setText(basePattern.getData("keepbasetittle='editableStart'", "keepbasetittle='editableFinish'"));
        lblName.setText(dynamiclyEvents.webSiteID.toUpperCase() + " TEMPLATE");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.JPanel();
        sidePanel2 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        upPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        txtTittle = new javax.swing.JTextField();
        txtSlogan = new javax.swing.JTextField();
        txtContentTittle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        lblSiteName = new javax.swing.JLabel();
        btnSave = new keeptoo.KButton();
        txtSignature = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg2.setBackground(new java.awt.Color(255, 255, 255));
        bg2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 204)));
        bg2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bg2MouseDragged(evt);
            }
        });
        bg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg2MousePressed(evt);
            }
        });
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel2.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(85, 65, 118));
        jPanel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel25MousePressed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 204, 204));
        jLabel49.setText("Anasayfa İşlemleri");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N

        jPanel22.setBackground(new java.awt.Color(85, 65, 118));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Anasayfa İşlemleri");
        jPanel22.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel22.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel24.setBackground(new java.awt.Color(85, 65, 118));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Anasayfa İşlemleri");
        jPanel24.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel24.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel23.setBackground(new java.awt.Color(85, 65, 118));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Anasayfa İşlemleri");
        jPanel23.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel23.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel24.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 70));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addGap(30, 30, 30)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 70));

        jPanel5.setBackground(new java.awt.Color(64, 43, 100));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Hakkımızda İşlemleri");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat-4-24.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(85, 65, 118));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Anasayfa İşlemleri");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Anasayfa İşlemleri");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Anasayfa İşlemleri");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 70));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 70));

        jPanel9.setBackground(new java.awt.Color(64, 43, 100));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Blog İşlemleri");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/literature-24.png"))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(85, 65, 118));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Anasayfa İşlemleri");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel11.setBackground(new java.awt.Color(85, 65, 118));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Anasayfa İşlemleri");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel12.setBackground(new java.awt.Color(85, 65, 118));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Anasayfa İşlemleri");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 70));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 310, 70));

        jPanel13.setBackground(new java.awt.Color(64, 43, 100));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel13MousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("İletişim İşlemleri");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile-phone-8-24.png"))); // NOI18N

        jPanel14.setBackground(new java.awt.Color(85, 65, 118));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Anasayfa İşlemleri");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel15.setBackground(new java.awt.Color(85, 65, 118));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Anasayfa İşlemleri");
        jPanel15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel16.setBackground(new java.awt.Color(85, 65, 118));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Anasayfa İşlemleri");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home16pxwhite.png"))); // NOI18N
        jPanel16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 70));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidePanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 310, 70));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("KeepHTML");
        sidePanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));
        sidePanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        jLabel40.setText("We 🖤  KeepHTML");
        sidePanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 170, 40));

        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("We 🖤  KeepHTML");
        sidePanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 40));

        bg2.add(sidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 320, 760));

        upPanel.setBackground(new java.awt.Color(122, 22, 221));
        upPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));
        upPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 510, 60));
        upPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 220, 50));
        upPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 50));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 0, 153));
        jLabel39.setText("X");
        jLabel39.setFocusTraversalPolicyProvider(true);
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        upPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 20, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Şu anda KeepHTML;");
        upPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        bg2.add(upPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1080, 170));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTittle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTittle.setText("Site Başlığı");
        txtTittle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 153)));
        jPanel17.add(txtTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 500, 40));

        txtSlogan.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtSlogan.setText("Slogan");
        txtSlogan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 153)));
        jPanel17.add(txtSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 500, 20));

        txtContentTittle.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtContentTittle.setText("İçerik Başlığı");
        txtContentTittle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 0, 153)));
        jPanel17.add(txtContentTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 440, 30));

        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtContent.setLineWrap(true);
        txtContent.setRows(5);
        txtContent.setText("İçerik");
        txtContent.setBorder(null);
        jScrollPane1.setViewportView(txtContent);

        jPanel17.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 440, 140));

        lblSiteName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSiteName.setForeground(new java.awt.Color(204, 204, 204));
        lblSiteName.setText("Site Başlığı");
        jPanel17.add(lblSiteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 550, 30));

        btnSave.setText("Kaydet");
        btnSave.setkEndColor(new java.awt.Color(255, 51, 255));
        btnSave.setkHoverEndColor(new java.awt.Color(153, 0, 153));
        btnSave.setkStartColor(new java.awt.Color(51, 0, 153));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel17.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        txtSignature.setText("İmza");
        jPanel17.add(txtSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 440, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aboutPageBackground_700x500.jpg"))); // NOI18N
        jPanel17.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 590));

        bg2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 1080, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        File file = new File(path + "\\data\\templates\\Moschino\\about.html");
        BasePattern basePattern = new BasePattern(file);
        basePattern.readFile("keepbasetittle='editableStart'", "keepbasetittle='editableFinish'", txtTittle.getText());
        basePattern.readFile("keepslogan='editableStart'", "keepslogan='editableFinish'", txtSlogan.getText());
        basePattern.readFile("keepstatement='editableStart'", "keepstatement='editableFinish'", txtContent.getText());
        basePattern.readFile("keeptittle='editableStart'", "keeptittle='editableFinish'", txtContentTittle.getText());
        basePattern.readFile("keepsignature='editableStart'", "keepsignature='editableFinish'", txtSignature.getText());
        basePattern.readFile("keeptdown='editableStart'", "keeptdown='editableFinish'", txtTittle.getText());
        JOptionPane.showMessageDialog(null, "Başarılı!", "InfoBox:Kayıt Durumu", JOptionPane.INFORMATION_MESSAGE);
        lblSiteName.setText(txtTittle.getText());
    }//GEN-LAST:event_btnSaveActionPerformed
//htmlParser
    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void bg2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg2MouseDragged
        // TODO add your handling code here:
        new Drag(bg2).moveWindow(evt);
    }//GEN-LAST:event_bg2MouseDragged

    private void bg2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg2MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bg2MouseEntered

    private void bg2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg2MousePressed
        new Drag(bg2).onPress(evt);
    }//GEN-LAST:event_bg2MousePressed

    private void jPanel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25MousePressed
        // TODO add your handling code here:
        panelColors.setColor(jPanel25, new Color(85,65,118));
        panelColors.setColor(jPanel5, new Color(64,43,100));
        panelColors.setColor(jPanel9, new Color(64,43,100));
        panelColors.setColor(jPanel13, new Color(64,43,100));
        
    }//GEN-LAST:event_jPanel25MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        panelColors.setColor(jPanel5, new Color(85,65,118));
        panelColors.setColor(jPanel25, new Color(64,43,100));
        panelColors.setColor(jPanel9, new Color(64,43,100));
        panelColors.setColor(jPanel13, new Color(64,43,100));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
        panelColors.setColor(jPanel9, new Color(85,65,118));
        panelColors.setColor(jPanel25, new Color(64,43,100));
        panelColors.setColor(jPanel5, new Color(64,43,100));
        panelColors.setColor(jPanel13, new Color(64,43,100));
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MousePressed
        // TODO add your handling code here:
        panelColors.setColor(jPanel13, new Color(85,65,118));
        panelColors.setColor(jPanel25, new Color(64,43,100));
        panelColors.setColor(jPanel9, new Color(64,43,100));
        panelColors.setColor(jPanel5, new Color(64,43,100));
    }//GEN-LAST:event_jPanel13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(webSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(webSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(webSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(webSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new webSite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private keeptoo.KButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSiteName;
    private javax.swing.JPanel sidePanel2;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtContentTittle;
    private javax.swing.JTextField txtSignature;
    private javax.swing.JTextField txtSlogan;
    private javax.swing.JTextField txtTittle;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
